name: Docker Image CI

on:
 workflow_dispatch:
   inputs:
     DOCKER_ACTION:
       description: "Docker Action"
       required: true
       default: "build"
       type: choice
       options:
         - build
         - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      if: "${{ github.event.inputs.DOCKER_ACTION == 'build' || 'push' }}"
      run: docker build . --file Dockerfile -t jamesrelph/academytest:latest
    - name: Push the Docker image
      if: "${{ github.event.inputs.DOCKER_ACTION == 'push' }}"
      run: docker push jamesrelph/academytest
